### PR TITLE
fix - process stuck in infinite loop after reading badly formatted me…

### PR DESCRIPTION
**Pull request by julnicolas**

### CODE REVIEW

**Comment by hartfordfive** [comment]
Missing version increment in VERSION.txt.

**Comment by julnicolas** [comment]
No it isn't, I updated the version to 0.6.0 in VERSION.txt (it was at 0.5.0) before.

Or I missed something.

**Comment by hartfordfive** [comment]
> No it doesn't, I updated the version to 0.6.0 in VERSION.txt (it was at 0.5.0) before.
> 
> Or I missed something.

My apologies, I didn't notice you already changed it.

👍

**Comment by julnicolas** [comment]
Is it OK to merge @hartfordfive ?

**Pull request merged**
